# action.yml
name: 'sgrep-lint'
description: 'Run sgrep-lint with the given config and return the findings'
icon: 'align-left'
inputs:
  config:  # id of input
    description: 'config'
  targets:
    description: 'targets'
outputs:
  findings: # id of output
    description: 'The sgrep findings'
runs:
  using: 'docker'
  image: 'returntocorp/sgrep'
  args:
    - ${{ inputs.who-to-greet }}
