# action.yml
name: 'sgrep-lint'
description: 'Run sgrep-lint with the given config and return the findings'
branding:
  icon: 'align-left'
  color: 'gray-dark'
icon: 'align-left'
inputs:
  error:
    description: 'action exits 1 if the findings are find thus breaking the build'
    required: false
    default: true
  config:
    description: 'config'
  targets:
    description: 'targets'
outputs:
  output:
    description: 'output of sgrep'
runs:
  using: 'docker'
  image: 'Dockerfile'
