# action.yml
name: 'semgrep-action'
description: 'Run semgrep with the given config and return the findings'
branding:
  icon: 'align-left'
  color: 'gray-dark'
icon: 'align-left'
inputs:
  error:
    description: 'action exits 1 if the findings are find thus breaking the build'
  config:
    description: 'config arg'
  output:
    description: 'output arg'
  targets:
    description: 'targets'
outputs:
  output:
    description: 'output of semgrep'
runs:
  using: 'docker'
  image: 'Dockerfile'
