name: Self Test

on: [push]

jobs:
  self_test:
    runs-on: ubuntu-latest
    name: A job to run semgrep
    steps:
      - uses: actions/checkout@v2
      - name: semgrep action step
        id: semgrep
        uses: returntocorp/semgrep-action@develop
        with:
          config: https://semgrep.live/c/r/r2c
          targets: tests

      - name: Get the output from semgrep
        run: echo "semgrep ${{ steps.semgrep.outputs.output }}"