name: Tests

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  test-semgrep:
    name: Live runs of action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - id: semgrep-app-config
        name: with semgrep-app connection
        uses: ./tests/local-image-action
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
          publishDeployment: "1"
      - id: semgrep-live-registry-id
        name: with a semgrep.live Registry ID
        uses: ./tests/local-image-action
        with:
          config: https://semgrep.live/r/all
      - id: semgrep-live-snippet-id
        name: with a semgrep.live Snippet ID
        uses: ./tests/local-image-action
        with:
          config: https://semgrep.live/underyx:never-match
      - id: semgrep-live-pack-id
        name: with a semgrep.live Pack ID
        uses: ./tests/local-image-action
        with:
          config: https://semgrep.live/p/r2c
      - id: semgrep-sarif-report
        name: with SARIF report
        uses: ./tests/local-image-action
        with:
          config: https://semgrep.live/p/r2c
          generateSarif: "1"
      - name: Clean up SARIF file
        run: rm -f semgrep.sarif
      - id: allow-failure
        name: with allowing failure
        uses: ./tests/local-image-action
        with:
          config: https://semgrep.live/underyx:number-1
          allowFailure: "1"
